behaviors:
  RollerBall:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      learning_rate: 1.0e-4
      beta: 5.0e-5
      epsilon: 0.1
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.92
        strength: 1.0
    max_steps: 500000
    time_horizon: 32
    summary_freq: 10000